'use client'
import {Home,Search,Heart,MessageSquare,User,Camera,MapPin,Phone,Mail,Plus} from 'lucide-react'
import {useState} from 'react'
const props=[
  {id:'1',address:'123 Ocean Dr',city:'Fort Myers',price:450000,beds:3,baths:2,sqft:2100},
  {id:'2',address:'456 Palm Ave',city:'Cape Coral',price:325000,beds:2,baths:2,sqft:1500},
]
export default function Mobile(){
  const[activeTab,setActiveTab]=useState<'search'|'saved'|'leads'|'profile'>('search')
  return(
    <div className="min-h-screen bg-gray-50 pb-20">
      <header className="bg-blue-600 text-white p-4 sticky top-0 z-10"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Home className="w-6 h-6"/><span className="font-bold text-lg">CR Realtor</span></div><button className="p-2 hover:bg-blue-700 rounded-lg"><Camera className="w-6 h-6"/></button></div></header>
      <main className="p-4">
        {activeTab==='search'&&<div><div className="mb-4"><div className="relative"><Search className="absolute left-3 top-3 w-5 h-5 text-gray-400"/><input type="text" placeholder="Search by city or ZIP..." className="w-full pl-10 pr-4 py-3 border rounded-lg shadow-sm focus:ring-2 focus:ring-blue-500"/></div></div><div className="space-y-4">{props.map(p=><div key={p.id} className="bg-white rounded-lg shadow overflow-hidden"><div className="h-48 bg-gradient-to-br from-blue-500 to-blue-600 flex items-center justify-center"><Home className="w-16 h-16 text-white/50"/></div><div className="p-4"><div className="flex items-start justify-between mb-2"><div><p className="font-semibold text-lg">{p.address}</p><p className="text-sm text-gray-600 flex items-center gap-1"><MapPin className="w-4 h-4"/>{p.city}</p></div><button className="p-2 hover:bg-gray-100 rounded-full"><Heart className="w-6 h-6 text-gray-400"/></button></div><p className="text-2xl font-bold text-green-600 mb-2">${p.price.toLocaleString()}</p><div className="flex gap-4 text-sm text-gray-600 mb-3"><span>{p.beds} beds</span><span>•</span><span>{p.baths} baths</span><span>•</span><span>{p.sqft} sqft</span></div><div className="grid grid-cols-2 gap-2"><button className="bg-blue-600 text-white py-2 rounded-lg font-medium">Contact Agent</button><button className="border border-gray-300 py-2 rounded-lg font-medium">View Details</button></div></div></div>)}</div></div>}
        {activeTab==='saved'&&<div className="text-center py-12"><Heart className="w-16 h-16 text-gray-400 mx-auto mb-4"/><p className="text-gray-600">No saved properties yet</p></div>}
        {activeTab==='leads'&&<div><button className="w-full bg-blue-600 text-white p-4 rounded-lg font-medium mb-4 flex items-center justify-center gap-2"><Plus className="w-5 h-5"/>Capture New Lead</button><div className="space-y-3">{[{name:'John Smith',phone:'(555) 123-4567',email:'john@email.com',status:'new'}].map((l,i)=><div key={i} className="bg-white p-4 rounded-lg shadow"><p className="font-semibold">{l.name}</p><p className="text-sm text-gray-600 flex items-center gap-2 mt-1"><Phone className="w-4 h-4"/>{l.phone}</p><p className="text-sm text-gray-600 flex items-center gap-2"><Mail className="w-4 h-4"/>{l.email}</p><span className="inline-block mt-2 px-2 py-1 bg-green-100 text-green-700 text-xs rounded">{l.status}</span></div>)}</div></div>}
        {activeTab==='profile'&&<div className="bg-white rounded-lg shadow p-6"><div className="text-center mb-6"><div className="w-24 h-24 bg-gray-200 rounded-full mx-auto mb-4 flex items-center justify-center"><User className="w-12 h-12 text-gray-400"/></div><h2 className="text-xl font-bold">Your Agent</h2><p className="text-gray-600">Licensed Real Estate Professional</p></div><div className="space-y-3"><button className="w-full py-3 border rounded-lg hover:bg-gray-50 font-medium">Edit Profile</button><button className="w-full py-3 border rounded-lg hover:bg-gray-50 font-medium">Notifications</button><button className="w-full py-3 border rounded-lg hover:bg-gray-50 font-medium">Settings</button></div></div>}
      </main>
      <nav className="fixed bottom-0 left-0 right-0 bg-white border-t flex justify-around py-3"><button onClick={()=>setActiveTab('search')} className={`flex flex-col items-center gap-1 ${activeTab==='search'?'text-blue-600':'text-gray-400'}`}><Search className="w-6 h-6"/><span className="text-xs">Search</span></button><button onClick={()=>setActiveTab('saved')} className={`flex flex-col items-center gap-1 ${activeTab==='saved'?'text-blue-600':'text-gray-400'}`}><Heart className="w-6 h-6"/><span className="text-xs">Saved</span></button><button onClick={()=>setActiveTab('leads')} className={`flex flex-col items-center gap-1 ${activeTab==='leads'?'text-blue-600':'text-gray-400'}`}><MessageSquare className="w-6 h-6"/><span className="text-xs">Leads</span></button><button onClick={()=>setActiveTab('profile')} className={`flex flex-col items-center gap-1 ${activeTab==='profile'?'text-blue-600':'text-gray-400'}`}><User className="w-6 h-6"/><span className="text-xs">Profile</span></button></nav>
    </div>
  )
}
